# Eureka Server Configuration
server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      access: read_only

# Spring application configuration
spring:
  application:
    name: eureka-server

# Eureka server and client configuration
eureka:
  server:
    enable-self-preservation: false  # Disable self-preservation mode for development
    eviction-interval-timer-in-ms: 2000  # Interval for evicting expired instances (2 seconds)

  client:
    healthcheck.enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server/eureka/

  instance:
    prefer-ip-address: true  # Use IP address instead of hostname for registration
    lease-renewal-interval-in-seconds: 30  # Standard heartbeat interval
    lease-expiration-duration-in-seconds: 90  # Standard expiration duration

# Logging configuration for debugging
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO