# Eureka Server Configuration
server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      access: read_only

# Spring application configuration
spring:
  application:
    name: eureka-server

# Eureka server and client configuration
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000

  client:
    refresh.enable: false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server/eureka/

# Logging configuration for debugging
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO