#Standalone Properties
server.port: 8761

spring:
  config.activate.on-profile: standalone
  application.name: eureka-server

eureka:
  server:
    enable-self-preservation: true  # Self-preservation mode to allow immediate removal of expired instances
    eviction-interval-timer-in-ms: 2000  # Run eviction task every 2 second to remove timed-out instances (default is 60,000 ms)

  instance:
  client:
    register-with-eureka: false
    fetch-registry: false

